# Generated by Django 5.2 on 2025-04-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="zohooauthtokens",
            name="user",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="crm.user"
            ),
            preserve_default=False,
        ),
    ]
