# Generated by Django 5.2 on 2025-04-24 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_user_zohooauthtokens_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="zohooauthtokens",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="zohooauthtokens",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="zohooauthtokens",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="zohooauthtokens",
            name="token_expiry_time",
            field=models.DateTimeField(default="2025-01-01 00:00:00"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
