# Generated by Django 4.2.11 on 2025-06-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_zohooauthtokens_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="ZohoOAuthTokens",
        ),
    ]
